name: kalender
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.0
  sqflite: ^2.0.2+1
  path: ^1.8.1
  intl: ^0.18.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true